# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\naeem\Desktop\New folder (2)\Digital.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from HELP import Ui_HELP
class Ui_MainWindow(object):
    def open_help(self) :
        self.window = QtWidgets.QWidget()
        self.ui = Ui_HELP()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 485)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/zo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget\n"
"{\n"
"background-color: rgb(202, 247, 255);\n"
"}\n"
"QMenuBar{\n"
"\n"
"}\n"
"QGroupBox{\n"
"border: 4px solid;\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"border : 2px solid rgb(85, 255, 127);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QLabel{\n"
"font: 75 14pt \"Arial\";\n"
"}\n"
" QComboBox {\n"
"    border: 1px solid ;\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 16pt \"Arial\";\n"
"\n"
" }\n"
"QLineEdit {\n"
"     border: 2px solid rgb(0, 255, 127);\n"
"     background: white;\n"
"    \n"
"    \n"
"    font: 75 16pt \"MS Shell Dlg 2\";\n"
" }\n"
"\n"
"QLineEdit:hover {\n"
"border-color: rgb(170, 0, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"border-color: rgb(50, 0, 250);\n"
"   border-radius: 10px;\n"
"   color: #11FF00;\n"
"   font-family: Arial;\n"
"   font-size: 20px;\n"
"   font-weight: 200;\n"
"\n"
"   background-color: #3200FA;\n"
"\n"
"   text-decoration: none;\n"
"   display: inline-block;\n"
"   cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background: #2BAAFF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(86, 12, 198);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.ns_number = QtWidgets.QLineEdit(self.groupBox)
        self.ns_number.setObjectName("ns_number")
        self.gridLayout_5.addWidget(self.ns_number, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.ns_from = QtWidgets.QComboBox(self.groupBox)
        self.ns_from.setCurrentText("")
        self.ns_from.setMaxVisibleItems(6)
        self.ns_from.setObjectName("ns_from")
        self.gridLayout_5.addWidget(self.ns_from, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        self.ns_to = QtWidgets.QComboBox(self.groupBox)
        self.ns_to.setMaxVisibleItems(6)
        self.ns_to.setObjectName("ns_to")
        self.gridLayout_5.addWidget(self.ns_to, 2, 1, 1, 1)
        self.ns_btn = QtWidgets.QPushButton(self.groupBox)
        self.ns_btn.setObjectName("ns_btn")
        self.gridLayout_5.addWidget(self.ns_btn, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 4, 0, 1, 1)
        self.ns_out = QtWidgets.QLineEdit(self.groupBox)
        self.ns_out.setObjectName("ns_out")
        self.gridLayout_5.addWidget(self.ns_out, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.code_select = QtWidgets.QComboBox(self.groupBox_3)
        self.code_select.setMaxVisibleItems(6)
        self.code_select.setObjectName("code_select")
        self.code_select.addItem("")
        self.code_select.addItem("")
        self.code_select.addItem("")
        self.code_select.addItem("")
        self.code_select.addItem("")
        self.code_select.addItem("")
        self.code_select.addItem("")
        self.code_select.addItem("")
        self.code_select.addItem("")
        self.gridLayout_3.addWidget(self.code_select, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.code_number = QtWidgets.QLineEdit(self.groupBox_3)
        self.code_number.setObjectName("code_number")
        self.gridLayout_3.addWidget(self.code_number, 1, 1, 1, 1)
        self.code_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.code_btn.setObjectName("code_btn")
        self.gridLayout_3.addWidget(self.code_btn, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.code_out = QtWidgets.QLineEdit(self.groupBox_3)
        self.code_out.setObjectName("code_out")
        self.gridLayout_3.addWidget(self.code_out, 3, 1, 1, 1)
        self.code_btn.raise_()
        self.code_number.raise_()
        self.code_select.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.code_out.raise_()
        self.gridLayout.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cb_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.cb_btn.setObjectName("cb_btn")
        self.gridLayout_4.addWidget(self.cb_btn, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setStyleSheet("QGroupBox{\n"
"background-color: rgb(5, 21, 255);\n"
"}")
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.cb_base = QtWidgets.QComboBox(self.groupBox_4)
        self.cb_base.setMaxVisibleItems(6)
        self.cb_base.setObjectName("cb_base")
        self.gridLayout_4.addWidget(self.cb_base, 1, 1, 1, 1)
        self.cb_input = QtWidgets.QTextEdit(self.groupBox_4)
        self.cb_input.setTabStopWidth(80)
        self.cb_input.setObjectName("cb_input")
        self.gridLayout_4.addWidget(self.cb_input, 0, 1, 1, 3)
        self.cb_out = QtWidgets.QTextEdit(self.groupBox_4)
        self.cb_out.setTabStopWidth(80)
        self.cb_out.setObjectName("cb_out")
        self.gridLayout_4.addWidget(self.cb_out, 2, 1, 1, 3)
        self.cb_reverse = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb_reverse.setObjectName("cb_reverse")
        self.gridLayout_4.addWidget(self.cb_reverse, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.sc_first = QtWidgets.QLineEdit(self.groupBox_2)
        self.sc_first.setObjectName("sc_first")
        self.gridLayout_6.addWidget(self.sc_first, 0, 1, 1, 7)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.sc_second = QtWidgets.QLineEdit(self.groupBox_2)
        self.sc_second.setObjectName("sc_second")
        self.gridLayout_6.addWidget(self.sc_second, 1, 1, 1, 7)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 2, 0, 1, 1)
        self.sc_base = QtWidgets.QComboBox(self.groupBox_2)
        self.sc_base.setMaxVisibleItems(6)
        self.sc_base.setObjectName("sc_base")
        self.gridLayout_6.addWidget(self.sc_base, 2, 1, 1, 5)
        self.sc_add = QtWidgets.QPushButton(self.groupBox_2)
        self.sc_add.setObjectName("sc_add")
        self.gridLayout_6.addWidget(self.sc_add, 3, 1, 1, 1)
        self.sc_sub = QtWidgets.QPushButton(self.groupBox_2)
        self.sc_sub.setObjectName("sc_sub")
        self.gridLayout_6.addWidget(self.sc_sub, 3, 2, 1, 1)
        self.sc_mul = QtWidgets.QPushButton(self.groupBox_2)
        self.sc_mul.setObjectName("sc_mul")
        self.gridLayout_6.addWidget(self.sc_mul, 3, 3, 1, 1)
        self.sc_div = QtWidgets.QPushButton(self.groupBox_2)
        self.sc_div.setObjectName("sc_div")
        self.gridLayout_6.addWidget(self.sc_div, 3, 4, 1, 1)
        self.sc_correct = QtWidgets.QPushButton(self.groupBox_2)
        self.sc_correct.setObjectName("sc_correct")
        self.gridLayout_6.addWidget(self.sc_correct, 3, 5, 1, 1)
        self.sc_rem = QtWidgets.QPushButton(self.groupBox_2)
        self.sc_rem.setObjectName("sc_rem")
        self.gridLayout_6.addWidget(self.sc_rem, 3, 6, 1, 1)
        self.sc_pow = QtWidgets.QPushButton(self.groupBox_2)
        self.sc_pow.setEnabled(True)
        self.sc_pow.setObjectName("sc_pow")
        self.gridLayout_6.addWidget(self.sc_pow, 3, 7, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 4, 0, 1, 1)
        self.sc_out = QtWidgets.QLineEdit(self.groupBox_2)
        self.sc_out.setObjectName("sc_out")
        self.gridLayout_6.addWidget(self.sc_out, 4, 1, 1, 7)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lg_counter = QtWidgets.QLabel(self.groupBox_5)
        self.lg_counter.setObjectName("lg_counter")
        self.gridLayout_2.addWidget(self.lg_counter, 3, 4, 1, 1)
        self.lg_start = QtWidgets.QPushButton(self.groupBox_5)
        self.lg_start.setEnabled(False)
        self.lg_start.setObjectName("lg_start")
        self.gridLayout_2.addWidget(self.lg_start, 7, 1, 1, 7)
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 4, 0, 1, 1)
        self.lg_solution = QtWidgets.QLineEdit(self.groupBox_5)
        self.lg_solution.setObjectName("lg_solution")
        self.gridLayout_2.addWidget(self.lg_solution, 9, 1, 1, 7)
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 5, 0, 1, 1)
        self.lg_ttable = QtWidgets.QPushButton(self.groupBox_5)
        self.lg_ttable.setObjectName("lg_ttable")
        self.gridLayout_2.addWidget(self.lg_ttable, 3, 5, 1, 3)
        self.lg_zero = QtWidgets.QPushButton(self.groupBox_5)
        self.lg_zero.setObjectName("lg_zero")
        self.gridLayout_2.addWidget(self.lg_zero, 3, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 6, 0, 1, 1)
        self.lg_one = QtWidgets.QPushButton(self.groupBox_5)
        self.lg_one.setObjectName("lg_one")
        self.gridLayout_2.addWidget(self.lg_one, 3, 2, 1, 1)
        self.lg_ac = QtWidgets.QPushButton(self.groupBox_5)
        self.lg_ac.setObjectName("lg_ac")
        self.gridLayout_2.addWidget(self.lg_ac, 0, 4, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 9, 0, 1, 1)
        self.lg_pbar = QtWidgets.QProgressBar(self.groupBox_5)
        self.lg_pbar.setProperty("value", 0)
        self.lg_pbar.setAlignment(QtCore.Qt.AlignCenter)
        self.lg_pbar.setOrientation(QtCore.Qt.Horizontal)
        self.lg_pbar.setObjectName("lg_pbar")
        self.gridLayout_2.addWidget(self.lg_pbar, 8, 1, 1, 7)
        self.lg_out = QtWidgets.QTextEdit(self.groupBox_5)
        self.lg_out.setStyleSheet("font: 87 10pt \"Arial Black\";")
        self.lg_out.setUndoRedoEnabled(True)
        self.lg_out.setReadOnly(True)
        self.lg_out.setObjectName("lg_out")
        self.gridLayout_2.addWidget(self.lg_out, 1, 1, 2, 7)
        self.lg_del = QtWidgets.QPushButton(self.groupBox_5)
        self.lg_del.setObjectName("lg_del")
        self.gridLayout_2.addWidget(self.lg_del, 0, 6, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 5, 4, 1, 2)
        self.lg_time = QtWidgets.QComboBox(self.groupBox_5)
        self.lg_time.setObjectName("lg_time")
        self.lg_time.addItem("")
        self.lg_time.addItem("")
        self.lg_time.addItem("")
        self.lg_time.addItem("")
        self.lg_time.addItem("")
        self.lg_time.addItem("")
        self.lg_time.addItem("")
        self.lg_time.addItem("")
        self.lg_time.addItem("")
        self.lg_time.addItem("")
        self.gridLayout_2.addWidget(self.lg_time, 5, 1, 1, 3)
        self.lg_gates = QtWidgets.QComboBox(self.groupBox_5)
        self.lg_gates.setMaxVisibleItems(6)
        self.lg_gates.setObjectName("lg_gates")
        self.lg_gates.addItem("")
        self.lg_gates.addItem("")
        self.lg_gates.addItem("")
        self.lg_gates.addItem("")
        self.gridLayout_2.addWidget(self.lg_gates, 4, 1, 1, 7)
        self.lg_pin2 = QtWidgets.QCheckBox(self.groupBox_5)
        self.lg_pin2.setEnabled(False)
        self.lg_pin2.setCheckable(True)
        self.lg_pin2.setChecked(True)
        self.lg_pin2.setObjectName("lg_pin2")
        self.gridLayout_2.addWidget(self.lg_pin2, 6, 1, 1, 1)
        self.lg_pin3 = QtWidgets.QCheckBox(self.groupBox_5)
        self.lg_pin3.setEnabled(False)
        self.lg_pin3.setObjectName("lg_pin3")
        self.gridLayout_2.addWidget(self.lg_pin3, 6, 2, 1, 1)
        self.lg_pin4 = QtWidgets.QCheckBox(self.groupBox_5)
        self.lg_pin4.setEnabled(False)
        self.lg_pin4.setObjectName("lg_pin4")
        self.gridLayout_2.addWidget(self.lg_pin4, 6, 3, 1, 1)
        self.lg_pin5 = QtWidgets.QCheckBox(self.groupBox_5)
        self.lg_pin5.setEnabled(False)
        self.lg_pin5.setObjectName("lg_pin5")
        self.gridLayout_2.addWidget(self.lg_pin5, 6, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setEnabled(False)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 6, 5, 1, 3)
        self.lg_percent = QtWidgets.QLabel(self.groupBox_5)
        self.lg_percent.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(85, 85, 0);")
        self.lg_percent.setObjectName("lg_percent")
        self.gridLayout_2.addWidget(self.lg_percent, 8, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 10, 0, 1, 7)
        self.gridLayout.addWidget(self.groupBox_5, 0, 2, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1020, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.actionSimple_calculator = QtWidgets.QAction(MainWindow)
        self.actionSimple_calculator.setCheckable(True)
        self.actionSimple_calculator.setChecked(True)
        self.actionSimple_calculator.setObjectName("actionSimple_calculator")
        self.actionCodes = QtWidgets.QAction(MainWindow)
        self.actionCodes.setCheckable(True)
        self.actionCodes.setChecked(True)
        self.actionCodes.setObjectName("actionCodes")
        self.actionConvert_to_binary = QtWidgets.QAction(MainWindow)
        self.actionConvert_to_binary.setCheckable(True)
        self.actionConvert_to_binary.setChecked(True)
        self.actionConvert_to_binary.setObjectName("actionConvert_to_binary")
        self.actionLogic_gates = QtWidgets.QAction(MainWindow)
        self.actionLogic_gates.setCheckable(True)
        self.actionLogic_gates.setChecked(True)
        self.actionLogic_gates.setObjectName("actionLogic_gates")
        self.actionNumber_systems_2 = QtWidgets.QAction(MainWindow)
        self.actionNumber_systems_2.setCheckable(True)
        self.actionNumber_systems_2.setChecked(True)
        self.actionNumber_systems_2.setObjectName("actionNumber_systems_2")
        self.actionHelp_2 = QtWidgets.QAction(MainWindow)
        self.actionHelp_2.setObjectName("actionHelp_2")
        self.actionHelpMe = QtWidgets.QAction(MainWindow)
        self.actionHelpMe.setObjectName("actionHelpMe")
        
        self.actionHelpMe.triggered.connect(self.open_help)
                                            
        self.actionAboutMe = QtWidgets.QAction(MainWindow)
        self.actionAboutMe.setObjectName("actionAboutMe")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelpMe)
        self.menuHelp.addAction(self.actionAboutMe)
        self.menuView.addAction(self.actionNumber_systems_2)
        self.menuView.addAction(self.actionSimple_calculator)
        self.menuView.addAction(self.actionCodes)
        self.menuView.addAction(self.actionConvert_to_binary)
        self.menuView.addAction(self.actionLogic_gates)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ns_number, self.ns_from)
        MainWindow.setTabOrder(self.ns_from, self.ns_to)
        MainWindow.setTabOrder(self.ns_to, self.ns_btn)
        MainWindow.setTabOrder(self.ns_btn, self.ns_out)
        MainWindow.setTabOrder(self.ns_out, self.sc_first)
        MainWindow.setTabOrder(self.sc_first, self.sc_second)
        MainWindow.setTabOrder(self.sc_second, self.sc_base)
        MainWindow.setTabOrder(self.sc_base, self.sc_add)
        MainWindow.setTabOrder(self.sc_add, self.sc_sub)
        MainWindow.setTabOrder(self.sc_sub, self.sc_mul)
        MainWindow.setTabOrder(self.sc_mul, self.sc_div)
        MainWindow.setTabOrder(self.sc_div, self.sc_correct)
        MainWindow.setTabOrder(self.sc_correct, self.sc_rem)
        MainWindow.setTabOrder(self.sc_rem, self.sc_pow)
        MainWindow.setTabOrder(self.sc_pow, self.sc_out)
        MainWindow.setTabOrder(self.sc_out, self.code_select)
        MainWindow.setTabOrder(self.code_select, self.code_number)
        MainWindow.setTabOrder(self.code_number, self.code_btn)
        MainWindow.setTabOrder(self.code_btn, self.code_out)
        MainWindow.setTabOrder(self.code_out, self.cb_base)
        MainWindow.setTabOrder(self.cb_base, self.cb_reverse)
        MainWindow.setTabOrder(self.cb_reverse, self.cb_btn)
        MainWindow.setTabOrder(self.cb_btn, self.lg_gates)
        MainWindow.setTabOrder(self.lg_gates, self.lg_start)
        MainWindow.setTabOrder(self.lg_start, self.cb_input)
        MainWindow.setTabOrder(self.cb_input, self.cb_out)
        MainWindow.setTabOrder(self.cb_out, self.lg_out)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Digital"))
        self.groupBox.setTitle(_translate("MainWindow", "number systems"))
        self.label.setText(_translate("MainWindow", "Number"))
        self.label_2.setText(_translate("MainWindow", "From :"))
        self.label_3.setText(_translate("MainWindow", "To :"))
        self.ns_btn.setText(_translate("MainWindow", "convert"))
        self.label_4.setText(_translate("MainWindow", "Output : "))
        self.groupBox_3.setTitle(_translate("MainWindow", "codes"))
        self.label_9.setText(_translate("MainWindow", "select : "))
        self.code_select.setItemText(0, _translate("MainWindow", "ones\' complement"))
        self.code_select.setItemText(1, _translate("MainWindow", "twos\' complement"))
        self.code_select.setItemText(2, _translate("MainWindow", "ones\' decimal value"))
        self.code_select.setItemText(3, _translate("MainWindow", "twos\' decimal value"))
        self.code_select.setItemText(4, _translate("MainWindow", "binary to gary"))
        self.code_select.setItemText(5, _translate("MainWindow", "gray to binary"))
        self.code_select.setItemText(6, _translate("MainWindow", "gray decimal value"))
        self.code_select.setItemText(7, _translate("MainWindow", "decimal to BCD"))
        self.code_select.setItemText(8, _translate("MainWindow", "BCD to decimal"))
        self.label_10.setText(_translate("MainWindow", "Number : "))
        self.code_btn.setText(_translate("MainWindow", "convert"))
        self.label_11.setText(_translate("MainWindow", "Output : "))
        self.groupBox_4.setTitle(_translate("MainWindow", "AlphaNumeric systems"))
        self.cb_btn.setText(_translate("MainWindow", "convert"))
        self.label_12.setText(_translate("MainWindow", "Input : "))
        self.cb_reverse.setText(_translate("MainWindow", "reverse"))
        self.label_14.setText(_translate("MainWindow", "Base : "))
        self.label_13.setText(_translate("MainWindow", "Output : "))
        self.groupBox_2.setTitle(_translate("MainWindow", "simple calculator"))
        self.label_5.setText(_translate("MainWindow", "First  :"))
        self.label_6.setText(_translate("MainWindow", "Second :"))
        self.label_7.setText(_translate("MainWindow", "Base :"))
        self.sc_add.setText(_translate("MainWindow", "+"))
        self.sc_sub.setText(_translate("MainWindow", "-"))
        self.sc_mul.setText(_translate("MainWindow", "*"))
        self.sc_div.setText(_translate("MainWindow", "/"))
        self.sc_correct.setText(_translate("MainWindow", "//"))
        self.sc_rem.setText(_translate("MainWindow", "%"))
        self.sc_pow.setText(_translate("MainWindow", "^"))
        self.label_8.setText(_translate("MainWindow", "Output :"))
        self.groupBox_5.setTitle(_translate("MainWindow", "logic gates"))
        self.lg_counter.setText(_translate("MainWindow", "000"))
        self.lg_start.setText(_translate("MainWindow", "start"))
        self.label_16.setText(_translate("MainWindow", "Gates :"))
        self.label_18.setText(_translate("MainWindow", "Time :"))
        self.lg_ttable.setText(_translate("MainWindow", "Truth Table"))
        self.lg_zero.setText(_translate("MainWindow", "0"))
        self.label_21.setText(_translate("MainWindow", "pins :"))
        self.lg_one.setText(_translate("MainWindow", "1"))
        self.lg_ac.setText(_translate("MainWindow", "AC"))
        self.label_15.setText(_translate("MainWindow", "OutPut :"))
        self.label_17.setText(_translate("MainWindow", "solution :"))
        self.lg_del.setText(_translate("MainWindow", "Del"))
        self.label_22.setText(_translate("MainWindow", "minutes"))
        self.lg_time.setItemText(0, _translate("MainWindow", "default"))
        self.lg_time.setItemText(1, _translate("MainWindow", "1"))
        self.lg_time.setItemText(2, _translate("MainWindow", "2"))
        self.lg_time.setItemText(3, _translate("MainWindow", "5"))
        self.lg_time.setItemText(4, _translate("MainWindow", "10"))
        self.lg_time.setItemText(5, _translate("MainWindow", "15"))
        self.lg_time.setItemText(6, _translate("MainWindow", "20"))
        self.lg_time.setItemText(7, _translate("MainWindow", "30"))
        self.lg_time.setItemText(8, _translate("MainWindow", "45"))
        self.lg_time.setItemText(9, _translate("MainWindow", "60"))
        self.lg_gates.setItemText(0, _translate("MainWindow", "All Gates"))
        self.lg_gates.setItemText(1, _translate("MainWindow", "NAND, NOR"))
        self.lg_gates.setItemText(2, _translate("MainWindow", "NOT, AND, OR"))
        self.lg_gates.setItemText(3, _translate("MainWindow", "NOT, AND, OR, XOR"))
        self.lg_pin2.setText(_translate("MainWindow", "2"))
        self.lg_pin3.setText(_translate("MainWindow", "3"))
        self.lg_pin4.setText(_translate("MainWindow", "4"))
        self.lg_pin5.setText(_translate("MainWindow", "5"))
        self.label_19.setText(_translate("MainWindow", "......................"))
        self.lg_percent.setText(_translate("MainWindow", "00.000%"))
        self.label_20.setText(_translate("MainWindow", "NOT:!, AND:&, OR:|, NAND:$, NOR:=, XOR:+, XNOR:#"))
        self.menuFile.setTitle(_translate("MainWindow", "file"))
        self.menuHelp.setTitle(_translate("MainWindow", "help"))
        self.menuView.setTitle(_translate("MainWindow", "view"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "about"))
        self.actionHelp.setText(_translate("MainWindow", "help"))
        self.actionAbout_2.setText(_translate("MainWindow", "about"))
        self.actionSimple_calculator.setText(_translate("MainWindow", "simple calculator"))
        self.actionCodes.setText(_translate("MainWindow", "codes"))
        self.actionConvert_to_binary.setText(_translate("MainWindow", "AlphaNumeric systems"))
        self.actionLogic_gates.setText(_translate("MainWindow", "logic gates"))
        self.actionNumber_systems_2.setText(_translate("MainWindow", "number systems"))
        self.actionHelp_2.setText(_translate("MainWindow", "help"))
        self.actionHelpMe.setText(_translate("MainWindow", "help"))
        self.actionAboutMe.setText(_translate("MainWindow", "about"))

import photo_rc
