# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\AhmedNaeem\Desktop\python files\tree_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(903, 505)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/tree.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gridLayout_5 = QtWidgets.QGridLayout(Form)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.setting_box = QtWidgets.QGroupBox(Form)
        self.setting_box.setMinimumSize(QtCore.QSize(160, 90))
        self.setting_box.setMaximumSize(QtCore.QSize(160, 90))
        self.setting_box.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setting_box.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.setting_box.setObjectName("setting_box")
        self.black_btn = QtWidgets.QPushButton(self.setting_box)
        self.black_btn.setGeometry(QtCore.QRect(126, 41, 21, 21))
        self.black_btn.setMinimumSize(QtCore.QSize(21, 21))
        self.black_btn.setMaximumSize(QtCore.QSize(21, 21))
        self.black_btn.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color: rgb(25, 25, 25);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(0, 0, 0);\n"
"}")
        self.black_btn.setText("")
        self.black_btn.setObjectName("black_btn")
        self.classic_btn = QtWidgets.QPushButton(self.setting_box)
        self.classic_btn.setGeometry(QtCore.QRect(126, 18, 21, 21))
        self.classic_btn.setMinimumSize(QtCore.QSize(21, 21))
        self.classic_btn.setMaximumSize(QtCore.QSize(21, 21))
        self.classic_btn.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color: rgb(161, 161, 161);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(206, 206, 206);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(115, 115, 115);\n"
"}")
        self.classic_btn.setText("")
        self.classic_btn.setObjectName("classic_btn")
        self.export_btn = QtWidgets.QPushButton(self.setting_box)
        self.export_btn.setGeometry(QtCore.QRect(15, 15, 90, 22))
        self.export_btn.setMinimumSize(QtCore.QSize(90, 22))
        self.export_btn.setMaximumSize(QtCore.QSize(90, 22))
        self.export_btn.setObjectName("export_btn")
        self.green_btn = QtWidgets.QPushButton(self.setting_box)
        self.green_btn.setGeometry(QtCore.QRect(126, 64, 21, 21))
        self.green_btn.setMinimumSize(QtCore.QSize(21, 21))
        self.green_btn.setMaximumSize(QtCore.QSize(21, 21))
        self.green_btn.setStyleSheet("\n"
"QPushButton{\n"
"border-radius: 10px;\n"
"background-color: rgb(8, 177, 0);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"   background: rgb(34, 255, 34);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(40, 124, 25);\n"
"}")
        self.green_btn.setText("")
        self.green_btn.setObjectName("green_btn")
        self.lang_btn = QtWidgets.QPushButton(self.setting_box)
        self.lang_btn.setGeometry(QtCore.QRect(15, 40, 90, 22))
        self.lang_btn.setMinimumSize(QtCore.QSize(90, 22))
        self.lang_btn.setMaximumSize(QtCore.QSize(90, 22))
        self.lang_btn.setObjectName("lang_btn")
        self.line = QtWidgets.QFrame(self.setting_box)
        self.line.setGeometry(QtCore.QRect(105, 20, 20, 61))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.contact = QtWidgets.QLabel(self.setting_box)
        self.contact.setGeometry(QtCore.QRect(20, 65, 81, 20))
        self.contact.setAccessibleName("")
        self.contact.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contact.setOpenExternalLinks(True)
        self.contact.setObjectName("contact")
        self.gridLayout_5.addWidget(self.setting_box, 0, 0, 1, 1)
        self.search_box = QtWidgets.QGroupBox(Form)
        self.search_box.setMinimumSize(QtCore.QSize(200, 90))
        self.search_box.setMaximumSize(QtCore.QSize(200, 90))
        self.search_box.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.search_box.setObjectName("search_box")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.search_box)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.search_name_label = QtWidgets.QLabel(self.search_box)
        self.search_name_label.setObjectName("search_name_label")
        self.gridLayout_4.addWidget(self.search_name_label, 0, 0, 1, 1)
        self.search_LE = QtWidgets.QLineEdit(self.search_box)
        self.search_LE.setObjectName("search_LE")
        self.gridLayout_4.addWidget(self.search_LE, 0, 1, 1, 1)
        self.search_btn = QtWidgets.QPushButton(self.search_box)
        self.search_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.search_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.search_btn.setObjectName("search_btn")
        self.gridLayout_4.addWidget(self.search_btn, 0, 2, 1, 2)
        self.search_count_label = QtWidgets.QLabel(self.search_box)
        self.search_count_label.setObjectName("search_count_label")
        self.gridLayout_4.addWidget(self.search_count_label, 1, 0, 1, 1)
        self.search_res = QtWidgets.QLabel(self.search_box)
        self.search_res.setText("")
        self.search_res.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.search_res.setObjectName("search_res")
        self.gridLayout_4.addWidget(self.search_res, 1, 1, 1, 1)
        self.search_next_btn = QtWidgets.QPushButton(self.search_box)
        self.search_next_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.search_next_btn.setObjectName("search_next_btn")
        self.gridLayout_4.addWidget(self.search_next_btn, 1, 2, 1, 1)
        self.search_back_btn = QtWidgets.QPushButton(self.search_box)
        self.search_back_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.search_back_btn.setObjectName("search_back_btn")
        self.gridLayout_4.addWidget(self.search_back_btn, 1, 3, 1, 1)
        self.gridLayout_5.addWidget(self.search_box, 0, 1, 1, 1)
        self.profile_box = QtWidgets.QGroupBox(Form)
        self.profile_box.setMaximumSize(QtCore.QSize(1200, 90))
        self.profile_box.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.profile_box.setObjectName("profile_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.profile_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.full_name = QtWidgets.QLabel(self.profile_box)
        self.full_name.setText("")
        self.full_name.setObjectName("full_name")
        self.gridLayout_3.addWidget(self.full_name, 0, 1, 1, 1)
        self.pro_count = QtWidgets.QLabel(self.profile_box)
        self.pro_count.setObjectName("pro_count")
        self.gridLayout_3.addWidget(self.pro_count, 4, 0, 1, 1)
        self.profile_count = QtWidgets.QLabel(self.profile_box)
        self.profile_count.setText("")
        self.profile_count.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.profile_count.setObjectName("profile_count")
        self.gridLayout_3.addWidget(self.profile_count, 4, 1, 1, 1)
        self.gender_label = QtWidgets.QLabel(self.profile_box)
        self.gender_label.setText("")
        self.gender_label.setObjectName("gender_label")
        self.gridLayout_3.addWidget(self.gender_label, 1, 1, 1, 1)
        self.pro_name = QtWidgets.QLabel(self.profile_box)
        self.pro_name.setObjectName("pro_name")
        self.gridLayout_3.addWidget(self.pro_name, 0, 0, 1, 1)
        self.pro_gender = QtWidgets.QLabel(self.profile_box)
        self.pro_gender.setMinimumSize(QtCore.QSize(45, 0))
        self.pro_gender.setMaximumSize(QtCore.QSize(45, 16777215))
        self.pro_gender.setObjectName("pro_gender")
        self.gridLayout_3.addWidget(self.pro_gender, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.profile_box, 0, 2, 1, 1)
        self.fam_frame = QtWidgets.QGroupBox(Form)
        self.fam_frame.setToolTip("")
        self.fam_frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fam_frame.setObjectName("fam_frame")
        self.gridLayout_5.addWidget(self.fam_frame, 1, 0, 1, 3)
        self.info_box = QtWidgets.QGroupBox(Form)
        self.info_box.setMaximumSize(QtCore.QSize(170, 1200))
        self.info_box.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.info_box.setObjectName("info_box")
        self.gridLayout = QtWidgets.QGridLayout(self.info_box)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.info_box)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.info_status = QtWidgets.QLabel(self.info_box)
        self.info_status.setObjectName("info_status")
        self.gridLayout.addWidget(self.info_status, 12, 0, 1, 1)
        self.child_name = QtWidgets.QLineEdit(self.info_box)
        self.child_name.setObjectName("child_name")
        self.gridLayout.addWidget(self.child_name, 4, 0, 1, 3)
        self.info_data = QtWidgets.QLabel(self.info_box)
        self.info_data.setObjectName("info_data")
        self.gridLayout.addWidget(self.info_data, 9, 0, 1, 1)
        self.child_list = QtWidgets.QListWidget(self.info_box)
        self.child_list.setObjectName("child_list")
        self.gridLayout.addWidget(self.child_list, 8, 0, 1, 3)
        self.add_btn = QtWidgets.QPushButton(self.info_box)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout.addWidget(self.add_btn, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.info_box)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.data_list = QtWidgets.QTextEdit(self.info_box)
        self.data_list.setMaximumSize(QtCore.QSize(16777215, 500))
        self.data_list.setToolTip("")
        self.data_list.setTabChangesFocus(True)
        self.data_list.setPlaceholderText("")
        self.data_list.setObjectName("data_list")
        self.gridLayout.addWidget(self.data_list, 10, 0, 1, 3)
        self.del_btn = QtWidgets.QPushButton(self.info_box)
        self.del_btn.setObjectName("del_btn")
        self.gridLayout.addWidget(self.del_btn, 7, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.info_box)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 9, 1, 1, 1)
        self.gender_cb = QtWidgets.QComboBox(self.info_box)
        self.gender_cb.setObjectName("gender_cb")
        self.gender_cb.addItem("")
        self.gender_cb.addItem("")
        self.gridLayout.addWidget(self.gender_cb, 5, 2, 1, 1)
        self.info_son = QtWidgets.QLabel(self.info_box)
        self.info_son.setObjectName("info_son")
        self.gridLayout.addWidget(self.info_son, 3, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.info_box)
        self.save_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 11, 0, 1, 3)
        self.info_gender = QtWidgets.QLabel(self.info_box)
        self.info_gender.setObjectName("info_gender")
        self.gridLayout.addWidget(self.info_gender, 5, 0, 1, 1)
        self.status_show = QtWidgets.QLabel(self.info_box)
        self.status_show.setMinimumSize(QtCore.QSize(72, 0))
        self.status_show.setMaximumSize(QtCore.QSize(72, 16777215))
        self.status_show.setText("")
        self.status_show.setObjectName("status_show")
        self.gridLayout.addWidget(self.status_show, 12, 2, 1, 1)
        self.info_name = QtWidgets.QLabel(self.info_box)
        self.info_name.setObjectName("info_name")
        self.gridLayout.addWidget(self.info_name, 0, 0, 1, 1)
        self.edit_btn = QtWidgets.QPushButton(self.info_box)
        self.edit_btn.setObjectName("edit_btn")
        self.gridLayout.addWidget(self.edit_btn, 2, 2, 1, 1)
        self.name_LE = QtWidgets.QLineEdit(self.info_box)
        self.name_LE.setObjectName("name_LE")
        self.gridLayout.addWidget(self.name_LE, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.info_box, 0, 3, 2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.child_name, self.del_btn)
        Form.setTabOrder(self.del_btn, self.data_list)
        Form.setTabOrder(self.data_list, self.save_btn)
        Form.setTabOrder(self.save_btn, self.search_LE)
        Form.setTabOrder(self.search_LE, self.search_btn)
        Form.setTabOrder(self.search_btn, self.search_next_btn)
        Form.setTabOrder(self.search_next_btn, self.search_back_btn)
        Form.setTabOrder(self.search_back_btn, self.classic_btn)
        Form.setTabOrder(self.classic_btn, self.black_btn)
        Form.setTabOrder(self.black_btn, self.green_btn)
        Form.setTabOrder(self.green_btn, self.export_btn)
        Form.setTabOrder(self.export_btn, self.lang_btn)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "شجرة العائلة"))
        self.setting_box.setTitle(_translate("Form", "الضبط"))
        self.export_btn.setText(_translate("Form", "حفظ كصورة"))
        self.lang_btn.setText(_translate("Form", "English"))
        self.contact.setText(_translate("Form", "<html><head/><body><p align=\"center\"><a href=\"https://www.facebook.com/ahmednaeem1996\"><span style=\" font-weight:600; text-decoration: underline; color:#0000ff;\">contact me</span></a></p></body></html>"))
        self.search_box.setTitle(_translate("Form", "بحث"))
        self.search_name_label.setText(_translate("Form", "الاسم : "))
        self.search_btn.setText(_translate("Form", "بحث"))
        self.search_count_label.setText(_translate("Form", "العدد : "))
        self.search_next_btn.setText(_translate("Form", "<"))
        self.search_back_btn.setText(_translate("Form", ">"))
        self.profile_box.setTitle(_translate("Form", "البروفايل"))
        self.pro_count.setText(_translate("Form", "عدد النسل : "))
        self.pro_name.setText(_translate("Form", "الاسم : "))
        self.pro_gender.setText(_translate("Form", "النوع : "))
        self.fam_frame.setTitle(_translate("Form", "شجرة العائلة"))
        self.info_box.setTitle(_translate("Form", "معلومات"))
        self.info_status.setText(_translate("Form", "الحالة : "))
        self.info_data.setText(_translate("Form", "البيانات :"))
        self.add_btn.setText(_translate("Form", "اضافة"))
        self.data_list.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.del_btn.setText(_translate("Form", "حذف"))
        self.gender_cb.setItemText(0, _translate("Form", "مذكر"))
        self.gender_cb.setItemText(1, _translate("Form", "مؤنث"))
        self.info_son.setText(_translate("Form", "الاولاد :"))
        self.save_btn.setText(_translate("Form", "حفظ"))
        self.info_gender.setText(_translate("Form", "النوع :"))
        self.info_name.setText(_translate("Form", "الاسم :"))
        self.edit_btn.setText(_translate("Form", "تغيير"))
import photo_rc
